### ISSUE TITLE
auth_token vs api_token?

### ISSUE THREAD

**Issue by excid3** [caddy-dns/vultr#7]
Ran into this error with Caddy today:

```
loading DNS provider module: loading module 'vultr': decoding module config: dns.providers.vultr: json: unknown field \"api_token\"
```

I was using the docs from the README here to configure Vultr DNS and had to change it from `api_token` to `auth_token`. Are the docs out of sync here?

**Comment by mholt** [comment]
Looks like the `APIToken` field is mapped to `auth_token` in JSON: https://github.com/libdns/vultr/blob/cd4cb5c12e511243a700fa2fa2f5e0675f7dd02b/provider.go#L17

@Xinayder could probably fix it real quickly!

**Comment by Xinayder** [comment]
Sorry for the late reply, I'll take a look and update it accordingly!
